### ISSUE TITLE
Using raw sql (cursors) with executemany breaks debug toolbar

### ISSUE THREAD

**Issue by eloff** [dcramer/django-debug-toolbar#15]
Relevant traceback:

File 'E:\Projects\farmforce\farmforce\fftenant\tags.py', line 77 in add_multiple_tags
  cursor.executemany(query, params)
File 'C:\Python27\lib\site-packages\django_debug_toolbar-0.8.5-py2.7.egg\debug_toolbar\panels\sql.py', line 199 in executemany
  'sql': self.db.ops.last_executed_query(self.cursor, sql, params),
File 'C:\Python27\lib\site-packages\django\db\backends\**init**.py', line 505 in last_executed_query
  return smart_unicode(sql) % u_params
TypeError: not all arguments converted during string formatting

**Comment by eloff** [comment]
It's not really sensible to format the query with a (potentially) very long list of params of tuples. Here's a patch that simply leaves the %s placeholders intact:

@@ -148,7 +148,7 @@ class DatabaseStatTracker(util.CursorDebugWrapper):

```
         # We keep `sql` to maintain backwards compatibility
         self.db.queries.append({
```
-                'sql': self.db.ops.last_executed_query(self.cursor, sql, params),
-                'sql': force_unicode(sql), # params is a list of tuples, we can't use db.ops.last_executed_query
               'duration': duration,
               'raw_sql': sql,
               'params': _params,

**Comment by eloff** [comment]
Eww... Hopefully you get the idea still. Why there's no upload patch feature I don't know, but if anyone knows how to post a diff on github, please share...

**Comment by dcramer** [comment]
Typically on GitHub you "Fork" a repository, then submit a pull request.

However, can you fork/submit against http://github.com/django-debug-toolbar/django-debug-toolbar
